import type express from 'express';
import { DisconnectReason, makeWASocket } from '@whiskeysockets/baileys';
import pino from 'pino';
import QRCode from 'qrcode';
import { authenticatedUser, type VerifiedFirebaseUser } from './server-auth';
import { adminDb } from './server-firebase-admin';
import { clearEncryptedAuthState, useEncryptedAuthState } from './message-auth-store';
import { authorizeDispatchUnit, safeInterruptionReason, waitForCampaignReady } from './message-dispatch-policy';
import { createMessageCampaign, findMessageCampaignByRequest, type CreateMessageCampaignInput } from './message-campaign-creation';
import { MESSAGE_CAMPAIGN_COLLECTIONS, type MessageCampaignDocument, type MessageCampaignRecipientDocument } from './src/services/messageCampaignSchema';
import { claimNextMessageRecipient, finalizeMessageRecipient, renewMessageRecipientLease, withMessageLeaseRenewal } from './message-campaign-worker';
import { recoverActiveMessageCampaigns, recoverMessageCampaign } from './message-campaign-recovery';
import { handleMessageRecipientFailure } from './message-campaign-retry';
import { UnitSessionRegistry, whatsappSessionVaultPath } from './message-session-scope';
import { messageDisconnectReason, messageQrExpiresAt } from './message-session-lifecycle';
import { acquireMessageSessionLock, releaseMessageSessionLock, renewMessageSessionLock } from './message-session-lock';

type Log={id:string;time:string;text:string;type:'info'|'success'|'warning'};
type Delivery={contact:string;status:'AGUARDANDO'|'ENVIADO'|'FALHA';processedAt?:string;error?:string};
type State={enabled:boolean;connectionStatus:'disconnected'|'connecting'|'qr'|'connected';currentQr:string;qrExpiresAt:string|null;accountPhone:string;accountName:string;lastConnectedAt:string|null;disconnectReason:string;disconnectKind:'none'|'intentional'|'abnormal'|'expired';isSending:boolean;progress:number;total:number;currentAction:string;logs:Log[];campaignStatus:'idle'|'running'|'paused'|'completed'|'stopped';successCount:number;errorCount:number;errorDetails:{contact:string;error:string}[];deliveryDetails:Delivery[];runId:string;activeUnitId:string;lastError:string;requiresNewQr:boolean};
type Session={unitId:string;state:State;socket:ReturnType<typeof makeWASocket>|null;connecting:boolean;generation:number;workerActive:boolean;intentionalDisconnect:boolean;qrTimer:ReturnType<typeof setTimeout>|null;lockTimer:ReturnType<typeof setInterval>|null;lockToken:number|null;actor?:VerifiedFirebaseUser};

const BASE_VAULT=process.env.WHATSAPP_AUTH_VAULT||'data/whatsapp/session.enc';
const MAX_CONTACTS=200;
const workerId=process.env.MESSAGE_WORKER_ID?.trim()||`message-worker-${crypto.randomUUID()}`;
const sessionInstanceId=`${process.env.RAILWAY_REPLICA_ID?.trim()||process.env.HOSTNAME?.trim()||'message-instance'}:${crypto.randomUUID()}`;
const SESSION_LOCK_LEASE_MS=60_000;
const SESSION_LOCK_RENEW_MS=20_000;
const initialState=(unitId:string):State=>({enabled:true,connectionStatus:'disconnected',currentQr:'',qrExpiresAt:null,accountPhone:'',accountName:'',lastConnectedAt:null,disconnectReason:'',disconnectKind:'none',isSending:false,progress:0,total:0,currentAction:'Aguardando conexão.',logs:[],campaignStatus:'idle',successCount:0,errorCount:0,errorDetails:[],deliveryDetails:[],runId:'',activeUnitId:unitId,lastError:'',requiresNewQr:false});
const sessions=new UnitSessionRegistry<Session>(unitId=>({unitId,state:initialState(unitId),socket:null,connecting:false,generation:0,workerActive:false,intentionalDisconnect:false,qrTimer:null,lockTimer:null,lockToken:null}));
const pause=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const log=(session:Session,text:string,type:Log['type']='info')=>{session.state.logs.unshift({id:crypto.randomUUID(),time:new Date().toLocaleTimeString('pt-BR'),text,type});session.state.logs=session.state.logs.slice(0,80);};
const publicState=(session:Session)=>({...session.state,errorDetails:session.state.errorDetails.slice(0,100),deliveryDetails:session.state.deliveryDetails.slice(0,200)});

async function audit(action:string,user:VerifiedFirebaseUser|undefined,unitId:string,details:Record<string,unknown>={}){try{await adminDb.collection('dispatch_audit').add({action,unitId,userId:user?.uid||'SYSTEM',profileId:user?.profileId||null,userEmail:user?.email||null,userRole:user?.role||'SYSTEM',timestamp:new Date().toISOString(),...details});}catch(error){console.error('Falha na auditoria:',error);}}
async function persistSession(session:Session){const state=session.state;await adminDb.collection('message_whatsapp_sessions').doc(session.unitId).set({unitId:session.unitId,connectionStatus:state.connectionStatus,accountPhone:state.accountPhone,accountName:state.accountName,lastConnectedAt:state.lastConnectedAt,disconnectReason:state.disconnectReason,disconnectKind:state.disconnectKind,qrExpiresAt:state.qrExpiresAt,updatedAt:new Date().toISOString()},{merge:true}).catch(error=>console.error('Falha ao persistir metadados da sessão:',error));}
async function releaseSessionLock(session:Session){if(session.lockTimer)clearInterval(session.lockTimer);session.lockTimer=null;const token=session.lockToken;session.lockToken=null;if(token!==null)await releaseMessageSessionLock(adminDb,session.unitId,sessionInstanceId,token).catch(()=>false);}
async function ownsSessionLock(session:Session){const token=session.lockToken;if(token===null)return false;return renewMessageSessionLock(adminDb,session.unitId,sessionInstanceId,token,new Date(),SESSION_LOCK_LEASE_MS).catch(()=>false);}
function startSessionLockHeartbeat(session:Session,token:number){if(session.lockTimer)clearInterval(session.lockTimer);session.lockToken=token;session.lockTimer=setInterval(async()=>{const renewed=await renewMessageSessionLock(adminDb,session.unitId,sessionInstanceId,token,new Date(),SESSION_LOCK_LEASE_MS).catch(()=>false);if(renewed||session.lockToken!==token)return;if(session.lockTimer)clearInterval(session.lockTimer);session.lockTimer=null;session.lockToken=null;session.generation++;session.connecting=false;session.intentionalDisconnect=true;session.state.isSending=false;session.state.connectionStatus='disconnected';session.state.disconnectKind='abnormal';session.state.disconnectReason='A instância perdeu o lock exclusivo da sessão.';session.state.currentAction='Sessão encerrada para evitar conexão duplicada.';try{session.socket?.end(new Error('Lock distribuído perdido.'));}catch{/* encerrada */}session.socket=null;void persistSession(session);void audit('SESSION_LOCK_LOST',session.actor,session.unitId,{instanceId:sessionInstanceId,fencingToken:token});},SESSION_LOCK_RENEW_MS);session.lockTimer.unref?.();}

async function connect(user:VerifiedFirebaseUser|undefined,unitId:string){
  const session=sessions.get(unitId),state=session.state;if(session.connecting||state.connectionStatus==='connected')return {success:true};session.actor=user;session.intentionalDisconnect=false;session.connecting=true;const generation=++session.generation;state.connectionStatus=state.currentQr?'qr':'connecting';state.currentAction='Inicializando conexão com o WhatsApp...';
  try{
    const lock=await acquireMessageSessionLock(adminDb,unitId,sessionInstanceId,new Date(),SESSION_LOCK_LEASE_MS);if(!lock){session.connecting=false;state.connectionStatus='disconnected';state.disconnectKind='abnormal';state.disconnectReason='Esta unidade já está conectada em outra instância do serviço.';state.currentAction='Conexão protegida por outra instância.';await persistSession(session);return {success:false,error:state.disconnectReason};}startSessionLockHeartbeat(session,lock.fencingToken);
    const {state:auth,saveCreds,clear}=await useEncryptedAuthState(whatsappSessionVaultPath(BASE_VAULT,unitId));
    const socket=makeWASocket({auth,printQRInTerminal:false,logger:pino({level:'silent'}),browser:[`Van’s Management - ${unitId}`,'Chrome','1.0.0']});session.socket=socket;socket.ev.on('creds.update',saveCreds);
    socket.ev.on('connection.update',async update=>{
      if(generation!==session.generation)return;const {connection,lastDisconnect,qr}=update;
      if(qr){if(session.qrTimer)clearTimeout(session.qrTimer);state.connectionStatus='qr';state.currentQr=await QRCode.toDataURL(qr);state.qrExpiresAt=messageQrExpiresAt();state.currentAction='Escaneie o QR Code para conectar.';state.lastError='';state.requiresNewQr=false;void persistSession(session);session.qrTimer=setTimeout(()=>{if(generation!==session.generation||state.connectionStatus!=='qr')return;state.currentQr='';state.qrExpiresAt=null;state.connectionStatus='disconnected';state.requiresNewQr=true;state.disconnectKind='expired';state.disconnectReason='O QR Code expirou antes da leitura.';state.currentAction='QR expirado. Gere um novo código.';session.intentionalDisconnect=true;try{session.socket?.end(new Error('QR Code expirado.'));}catch{/* encerrada */}void persistSession(session);void audit('QR_EXPIRED',session.actor,unitId);},60_000);session.qrTimer.unref?.();}
      if(connection==='open'){if(session.qrTimer)clearTimeout(session.qrTimer);session.qrTimer=null;session.connecting=false;state.connectionStatus='connected';state.currentQr='';state.qrExpiresAt=null;state.accountPhone=String(socket.user?.id||'').split(':')[0].split('@')[0];state.accountName=socket.user?.name||'Conta WhatsApp';state.lastConnectedAt=new Date().toISOString();state.disconnectKind='none';state.disconnectReason='';state.currentAction='WhatsApp conectado e pronto.';state.lastError='';state.requiresNewQr=false;log(session,'WhatsApp conectado.','success');void persistSession(session);void audit('CONNECTION_OPENED',session.actor,unitId,{accountPhone:state.accountPhone,accountName:state.accountName});void resume(session);}
      if(connection==='close'){if(session.qrTimer)clearTimeout(session.qrTimer);session.qrTimer=null;session.connecting=false;session.socket=null;const code=(lastDisconnect?.error as {output?:{statusCode?:number}}|undefined)?.output?.statusCode;const loggedOut=code===DisconnectReason.loggedOut;const intentional=session.intentionalDisconnect;state.connectionStatus='disconnected';state.currentQr='';state.qrExpiresAt=null;state.disconnectReason=intentional?(state.disconnectReason||'Desconectado pelo operador.'):messageDisconnectReason(lastDisconnect?.error,code);state.disconnectKind=intentional?'intentional':loggedOut?'expired':'abnormal';state.currentAction=intentional?'Sessão desconectada.':loggedOut?'Sessão expirada. Gere um novo QR Code.':'Queda detectada. Tentando reconectar...';state.requiresNewQr=loggedOut;if(loggedOut)await clear().catch(()=>undefined);await releaseSessionLock(session);void persistSession(session);void audit(intentional?'CONNECTION_DISCONNECTED':'CONNECTION_DROPPED',session.actor,unitId,{reasonCode:code||null,reason:state.disconnectReason});if(!intentional&&!loggedOut)setTimeout(()=>void connect(session.actor,unitId),3000);}
    });return {success:true};
  }catch(error){const reason=error instanceof Error?error.message:'Falha de conexão.';session.connecting=false;session.socket=null;state.connectionStatus='disconnected';state.lastError=reason;state.currentAction=reason;log(session,reason,'warning');await releaseSessionLock(session);return {success:false,error:reason};}
}

async function runCampaign(session:Session,campaign:MessageCampaignDocument,user?:VerifiedFirebaseUser){
  const state=session.state;if(session.workerActive||state.connectionStatus!=='connected'||!session.socket)return;const recovered=await recoverMessageCampaign(adminDb,campaign.id);if(!recovered||['CONCLUIDA','FALHOU'].includes(recovered.campaign.status))return;campaign=recovered.campaign;
  const snapshot=await adminDb.collection(MESSAGE_CAMPAIGN_COLLECTIONS.recipients).where('campaignId','==',campaign.id).get();const recipients=snapshot.docs.map(doc=>({id:doc.id,...doc.data()} as MessageCampaignRecipientDocument));const contacts=recipients.map(item=>item.normalizedPhone);const minDelay=Math.max(8,Math.min(120,Number(campaign.minDelaySeconds)||15));const maxDelay=Math.max(minDelay,Math.min(180,Number(campaign.maxDelaySeconds)||35));const typing=campaign.simulateTyping!==false;
  session.workerActive=true;Object.assign(state,{isSending:true,campaignStatus:'running',runId:campaign.id,activeUnitId:campaign.unitId,successCount:campaign.sentCount,errorCount:campaign.failedCount,errorDetails:[],total:recipients.length,progress:campaign.sentCount+campaign.deliveredCount+campaign.readCount+campaign.failedCount+campaign.cancelledCount,logs:[]});state.deliveryDetails=recipients.map(item=>({contact:item.normalizedPhone,status:item.status==='ENVIADO'?'ENVIADO':item.status==='FALHOU'?'FALHA':'AGUARDANDO',...(item.processedAt?{processedAt:item.processedAt}:{}),...(item.lastError?{error:item.lastError}:{})}));log(session,`Campanha ${campaign.name} carregada da fila persistente.`);
  try{
    await adminDb.collection(MESSAGE_CAMPAIGN_COLLECTIONS.campaigns).doc(campaign.id).set({status:'EM_PROCESSAMENTO',updatedAt:new Date().toISOString()},{merge:true});await adminDb.collection('message_dispatch_history').doc(campaign.id).set({name:campaign.name,createdAt:campaign.createdAt,unitId:campaign.unitId,total:contacts.length,contacts,message:campaign.message,minDelay,maxDelay,simulateTyping:typing,confirmedOptIn:campaign.confirmedOptIn===true,processed:state.progress,successCount:state.successCount,errorCount:state.errorCount,status:'EM_ANDAMENTO',deliveryDetails:state.deliveryDetails,createdBy:campaign.createdBy,createdByEmail:campaign.createdByEmail||''},{merge:true});
    while(state.isSending){
      if(!await waitForCampaignReady(state))break;if(!await ownsSessionLock(session))throw new Error('Lock exclusivo da sessão perdido antes do envio.');const claimed=await claimNextMessageRecipient(adminDb,{workerId,campaignId:campaign.id,unitId:campaign.unitId,leaseMs:90_000});if(!claimed)break;const contact=claimed.normalizedPhone,index=state.deliveryDetails.findIndex(item=>item.contact===contact),slot=index>=0?index:state.progress;let jid=`${contact}@s.whatsapp.net`,done=false;
      try{await withMessageLeaseRenewal({intervalMs:30_000,renew:()=>renewMessageRecipientLease(adminDb,claimed.id,workerId,new Date(),90_000),work:async()=>{const socket=session.socket;if(!socket)throw new Error('WhatsApp desconectado durante o envio.');state.currentAction=`Validando ${claimed.maskedPhone}...`;const available=await socket.onWhatsApp(contact);if(!available?.[0]?.exists)throw new Error('Número não encontrado no WhatsApp');jid=available[0].jid;if(typing){state.currentAction=`Preparando mensagem ${state.progress+1} de ${contacts.length}...`;await socket.sendPresenceUpdate('composing',jid);await pause(Math.min(6000,Math.max(1200,claimed.personalizedMessage.length*45)));await socket.sendPresenceUpdate('paused',jid);}if(!await waitForCampaignReady(state))throw new Error('Campanha interrompida antes do envio.');await socket.sendMessage(jid,{text:claimed.personalizedMessage});}});const at=new Date().toISOString();if(!await finalizeMessageRecipient(adminDb,claimed.id,workerId,'ENVIADO',{now:new Date(at)}))throw new Error('Lease expirado.');state.successCount++;done=true;state.deliveryDetails[slot]={contact,status:'ENVIADO',processedAt:at};log(session,`Mensagem enviada para ${claimed.maskedPhone}.`,'success');}
      catch(error){const detail=error instanceof Error?error.message:'Falha no envio';if(!state.isSending){await finalizeMessageRecipient(adminDb,claimed.id,workerId,'CANCELADO',{error:detail});done=true;}else{const failure=await handleMessageRecipientFailure(adminDb,{recipientId:claimed.id,workerId,error,baseDelayMs:30_000});if(failure?.decision.retry){const seconds=Math.ceil(failure.decision.delayMs/1000);state.currentAction=`Nova tentativa em ${seconds}s...`;log(session,`${state.currentAction} (${claimed.maskedPhone})`,'warning');for(let i=0;i<seconds&&state.isSending;i++)await pause(1000);}else{done=true;state.errorCount++;state.errorDetails.push({contact:claimed.maskedPhone,error:detail});state.deliveryDetails[slot]={contact,status:'FALHA',processedAt:new Date().toISOString(),error:detail};log(session,`Falha definitiva para ${claimed.maskedPhone}.`,'warning');}}}
      if(done)state.progress++;if(done&&state.progress<contacts.length&&state.isSending){const seconds=Math.floor(Math.random()*(maxDelay-minDelay+1))+minDelay;for(let i=0;i<seconds&&state.isSending;i++){if(!await waitForCampaignReady(state))break;await pause(1000);}}
    }
    if(state.isSending){await recoverMessageCampaign(adminDb,campaign.id);state.campaignStatus='completed';state.currentAction='Campanha concluída.';log(session,'Processamento concluído.','success');await audit('CAMPAIGN_COMPLETED',user,campaign.unitId,{runId:campaign.id,processed:state.progress});await adminDb.collection('message_dispatch_history').doc(campaign.id).set({status:'CONCLUIDO',finishedAt:new Date().toISOString(),processed:state.progress,successCount:state.successCount,errorCount:state.errorCount,errorDetails:state.errorDetails,deliveryDetails:state.deliveryDetails},{merge:true});}
  }catch(error){state.campaignStatus='stopped';state.currentAction='Campanha interrompida por falha.';log(session,state.currentAction,'warning');await audit('CAMPAIGN_FAILED',user,campaign.unitId,{runId:campaign.id,reason:error instanceof Error?error.message:'Falha'});await adminDb.collection(MESSAGE_CAMPAIGN_COLLECTIONS.campaigns).doc(campaign.id).set({status:'NA_FILA',updatedAt:new Date().toISOString()},{merge:true});}finally{state.isSending=false;session.workerActive=false;}
}

async function resume(session:Session){if(session.workerActive||session.state.connectionStatus!=='connected')return;try{const campaigns=await recoverActiveMessageCampaigns(adminDb,{unitId:session.unitId});for(const item of campaigns){if(session.state.connectionStatus!=='connected')break;await runCampaign(session,item.campaign);}}catch(error){console.error(`Falha ao retomar ${session.unitId}:`,error);}}
const requestedUnit=(req:express.Request)=>req.body?.unitId??req.query?.unitId;
const requireUnit=(req:express.Request,res:express.Response)=>{const decision=authorizeDispatchUnit(authenticatedUser(req),requestedUnit(req));if(!decision.allowed){res.status(decision.status).json({error:decision.error});return null;}if(decision.unitId==='ALL'){res.status(400).json({error:'Selecione uma unidade específica para usar o WhatsApp.'});return null;}return decision.unitId;};

export async function startMessageDispatchConnection(){const configured=(process.env.MESSAGE_AUTO_CONNECT_UNITS||'').split(',').map(item=>item.trim()).filter(Boolean);const active=await adminDb.collection(MESSAGE_CAMPAIGN_COLLECTIONS.campaigns).where('status','in',['NA_FILA','EM_PROCESSAMENTO']).get().catch(()=>null);const units=new Set([...configured,...(active?.docs.map(doc=>String(doc.data().unitId||'')).filter(unit=>unit&&unit!=='ALL')||[])]);for(const unitId of units)void connect(undefined,unitId);}

export function configureMessageDispatch(app:express.Express,auth:express.RequestHandler,role:express.RequestHandler){
  app.get('/api/message-dispatch/status',auth,role,(req,res)=>{const unitId=requireUnit(req,res);if(unitId)res.json(publicState(sessions.get(unitId)));});
  app.post('/api/message-dispatch/connect',auth,role,async(req,res)=>{const unitId=requireUnit(req,res);if(!unitId)return;const user=authenticatedUser(req);await audit('CONNECTION_REQUESTED',user,unitId);const result=await connect(user,unitId);result.success?res.status(202).json({success:true}):res.status(500).json({error:result.error});});
  app.post('/api/message-dispatch/disconnect',auth,role,async(req,res)=>{const unitId=requireUnit(req,res);if(!unitId)return;const session=sessions.get(unitId);if(session.state.isSending){res.status(409).json({error:'Pause ou encerre a campanha antes de desconectar.'});return;}session.intentionalDisconnect=true;session.generation++;session.connecting=false;if(session.qrTimer)clearTimeout(session.qrTimer);session.state.disconnectKind='intentional';session.state.disconnectReason='Desconectado pelo operador.';session.state.connectionStatus='disconnected';session.state.currentQr='';session.state.qrExpiresAt=null;session.state.currentAction='Sessão desconectada.';try{session.socket?.end(new Error('Desconectado pelo operador.'));}catch{/* encerrada */}session.socket=null;await releaseSessionLock(session);await persistSession(session);await audit('CONNECTION_DISCONNECTED',authenticatedUser(req),unitId,{reason:session.state.disconnectReason});res.json({success:true});});
  app.post('/api/message-dispatch/reconnect',auth,role,async(req,res)=>{const unitId=requireUnit(req,res);if(!unitId)return;const session=sessions.get(unitId);if(session.state.isSending){res.status(409).json({error:'Não é possível reconectar durante uma campanha.'});return;}session.intentionalDisconnect=true;session.generation++;session.connecting=false;try{session.socket?.end(new Error('Reconexão solicitada.'));}catch{/* encerrada */}session.socket=null;session.state.connectionStatus='disconnected';await releaseSessionLock(session);await audit('CONNECTION_RECONNECT_REQUESTED',authenticatedUser(req),unitId);const result=await connect(authenticatedUser(req),unitId);result.success?res.status(202).json({success:true}):res.status(500).json({error:result.error});});
  app.post('/api/message-dispatch/new-qr',auth,role,async(req,res)=>{const unitId=requireUnit(req,res);if(!unitId)return;const session=sessions.get(unitId);if(session.state.isSending){res.status(409).json({error:'Não é possível gerar QR durante uma campanha.'});return;}session.intentionalDisconnect=true;session.generation++;session.connecting=false;if(session.qrTimer)clearTimeout(session.qrTimer);try{session.socket?.end(new Error('Novo QR solicitado.'));}catch{/* encerrada */}session.socket=null;await releaseSessionLock(session);await clearEncryptedAuthState(whatsappSessionVaultPath(BASE_VAULT,unitId));Object.assign(session.state,initialState(unitId));await audit('CONNECTION_NEW_QR_REQUESTED',authenticatedUser(req),unitId);const result=await connect(authenticatedUser(req),unitId);result.success?res.status(202).json({success:true}):res.status(500).json({error:result.error});});
  app.post('/api/message-dispatch/reset-session',auth,role,async(req,res)=>{const unitId=requireUnit(req,res);if(!unitId)return;const session=sessions.get(unitId);if(session.state.isSending){res.status(409).json({error:'Existe campanha ativa nesta unidade.'});return;}session.generation++;session.connecting=false;try{session.socket?.end(new Error('Sessão redefinida.'));}catch{/* encerrada */}session.socket=null;await releaseSessionLock(session);await clearEncryptedAuthState(whatsappSessionVaultPath(BASE_VAULT,unitId));Object.assign(session.state,initialState(unitId));const result=await connect(authenticatedUser(req),unitId);result.success?res.status(202).json({success:true}):res.status(500).json({error:result.error});});
  for(const action of ['pause','resume'] as const)app.post(`/api/message-dispatch/${action}`,auth,role,async(req,res)=>{const unitId=requireUnit(req,res);if(!unitId)return;const session=sessions.get(unitId),state=session.state;if(!state.isSending){res.status(409).json({error:'Não existe campanha ativa nesta unidade.'});return;}state.campaignStatus=action==='pause'?'paused':'running';state.currentAction=action==='pause'?'Campanha pausada.':'Retomando campanha...';if(state.runId)await adminDb.collection(MESSAGE_CAMPAIGN_COLLECTIONS.campaigns).doc(state.runId).set({status:action==='pause'?'PAUSADA':'EM_PROCESSAMENTO',updatedAt:new Date().toISOString()},{merge:true});res.json({success:true});});
  app.post('/api/message-dispatch/stop',auth,role,async(req,res)=>{const unitId=requireUnit(req,res);if(!unitId)return;const session=sessions.get(unitId),state=session.state,reason=safeInterruptionReason(req.body?.reason);state.isSending=false;state.campaignStatus='stopped';state.currentAction=reason;if(state.runId){await adminDb.collection(MESSAGE_CAMPAIGN_COLLECTIONS.campaigns).doc(state.runId).set({status:'CANCELADA',cancelledCount:Math.max(0,state.total-state.progress),updatedAt:new Date().toISOString(),finishedAt:new Date().toISOString()},{merge:true});await adminDb.collection('message_dispatch_history').doc(state.runId).set({status:'INTERROMPIDO',finishedAt:new Date().toISOString(),interruptionReason:reason},{merge:true});}res.json({success:true});});
  app.post('/api/message-dispatch/start',auth,role,async(req,res)=>{const unitId=requireUnit(req,res);if(!unitId)return;const session=sessions.get(unitId),user=authenticatedUser(req);if(session.state.connectionStatus!=='connected'||!session.socket){res.status(409).json({error:'Conecte o WhatsApp desta unidade.'});return;}const message=String(req.body?.message||'').trim(),raw=Array.isArray(req.body?.contacts)?req.body.contacts:String(req.body?.contacts||'').split(/\r?\n/),contacts=[...new Set(raw.map((value:unknown)=>String(value).replace(/\D/g,'')).map(value=>(value.length===10||value.length===11)?`55${value}`:value).filter(value=>value.length>=12&&value.length<=13))],minDelay=Math.max(8,Math.min(120,Number(req.body?.minDelay)||15)),maxDelay=Math.max(minDelay,Math.min(180,Number(req.body?.maxDelay)||35)),typing=req.body?.simulateTyping!==false;if(req.body?.confirmedOptIn!==true||!message||message.length>4096||!contacts.length||contacts.length>MAX_CONTACTS){res.status(400).json({error:'Revise mensagem, contatos e autorização.'});return;}const requestIdempotencyKey=String(req.body?.idempotencyKey||req.get('Idempotency-Key')||'').trim();if(!requestIdempotencyKey){res.status(400).json({error:'Chave de solicitação ausente.'});return;}const input:CreateMessageCampaignInput={requestIdempotencyKey,unitId,name:String(req.body?.campaignName||'Disparo sem título').trim().slice(0,120),message,contacts,minDelaySeconds:minDelay,maxDelaySeconds:maxDelay,simulateTyping:typing,confirmedOptIn:true,createdBy:user?.uid||'SYSTEM',...(user?.email?{createdByEmail:user.email}:{})};if(session.workerActive){const prior=await findMessageCampaignByRequest(adminDb,input);if(prior.existing){res.json({success:true,total:prior.existing.totalRecipients,campaignId:prior.existing.id,reused:true});return;}res.status(409).json({error:'Já existe campanha ativa nesta unidade.'});return;}let persisted;try{persisted=await createMessageCampaign(adminDb,input);}catch(error){res.status(409).json({error:error instanceof Error?error.message:'Falha ao salvar.'});return;}if(persisted.reused){res.json({success:true,total:persisted.campaign.totalRecipients,campaignId:persisted.campaign.id,reused:true});return;}res.json({success:true,total:contacts.length,campaignId:persisted.campaign.id,reused:false});await audit('CAMPAIGN_STARTED',user,unitId,{runId:persisted.campaign.id,totalContacts:contacts.length});void runCampaign(session,persisted.campaign,user);});
}
