import type { CashClosing, CommissionBracket, DailyEntry, FinancialTransaction, PaymentRecord } from '../types';

export type RevenueComponents = { standaloneRevenue?: number | null; subscriptionRevenue?: number | null; productRevenue?: number | null };
export type RevenueComponent = keyof RevenueComponents;
export interface CashMovementSummary { cashIn: number; cashOut: number; cashBalance: number; recognizedRevenue: number; recognizedExpenses: number; commercialDiscounts: number; passThroughReceived: number; passThroughPaid: number; passThroughBalance: number; internalTransferNet: number }
export interface FinancialSummary extends CashMovementSummary { grossRevenue: number; netRevenue: number; totalExpenses: number; totalCommissions: number; internalSales: number; courtesyVolume: number; netCashFlow: number }

const finiteOrZero = (value: number | null | undefined) => Number.isFinite(Number(value)) ? Number(value) : 0;
export const roundMoney = (value: number) => Number(finiteOrZero(value).toFixed(2));
export const clampMoney = (value: number | null | undefined) => roundMoney(Math.max(0, finiteOrZero(value)));
export function calculateTotalRevenue(standaloneRevenue: number | null | undefined, subscriptionRevenue: number | null | undefined, productRevenue: number | null | undefined) { return roundMoney(clampMoney(standaloneRevenue) + clampMoney(subscriptionRevenue) + clampMoney(productRevenue)); }
export function calculateRevenueFromComponents(components: RevenueComponents) { return calculateTotalRevenue(components.standaloneRevenue, components.subscriptionRevenue, components.productRevenue); }
export function inferStandaloneRevenue(totalRevenue: number | null | undefined, subscriptionRevenue: number | null | undefined, productRevenue: number | null | undefined) { return clampMoney(finiteOrZero(totalRevenue) - clampMoney(subscriptionRevenue) - clampMoney(productRevenue)); }
export function replaceImportedRevenue(current: RevenueComponents, component: RevenueComponent, importedValue: number | null | undefined) { const components = { ...current, [component]: clampMoney(importedValue) }; return { components, totalRevenue: calculateRevenueFromComponents(components) }; }
export function applyCommercialDiscount(grossRevenue: number, discount: number) { return roundMoney(Math.max(0, clampMoney(grossRevenue) - clampMoney(discount))); }
export function calculateFee(grossAmount: number, percentage: number) { const rate = Math.min(100, Math.max(0, finiteOrZero(percentage))); const gross = clampMoney(grossAmount); const fee = roundMoney(gross * rate / 100); return { gross, percentage: rate, fee, net: roundMoney(gross - fee) }; }
export function calculateCommissionByRevenue(revenue: number, brackets: CommissionBracket[]) { const safeRevenue = clampMoney(revenue); const bracket = [...brackets].sort((a, b) => a.minimumRevenue - b.minimumRevenue).find(item => safeRevenue >= item.minimumRevenue && safeRevenue <= item.maximumRevenue); return { bracket, percentage: bracket?.percentage || 0, commission: bracket ? roundMoney(safeRevenue * bracket.percentage / 100) : 0 }; }
export function calculatePaymentTotals(payment: Pick<PaymentRecord, 'commissionAvulso' | 'commissionProductGeneral' | 'commissionProductAvant' | 'commissionSubscriptions' | 'discount' | 'discounts'>) { const grossCommission = roundMoney(clampMoney(payment.commissionAvulso) + clampMoney(payment.commissionProductGeneral) + clampMoney(payment.commissionProductAvant) + clampMoney(payment.commissionSubscriptions)); const discounts = payment.discounts?.length ? payment.discounts.reduce((sum, item) => sum + clampMoney(item.value), 0) : clampMoney(payment.discount); return { grossCommission, discounts: roundMoney(discounts), netPayment: applyCommercialDiscount(grossCommission, discounts) }; }
export function calculateReversalEffect(originalEffect: number, alreadyReversed = 0) { return roundMoney(-(finiteOrZero(originalEffect) - finiteOrZero(alreadyReversed))); }

const natureOf = (transaction: FinancialTransaction) => transaction.movementNature || (transaction.type === 'INCOME' ? 'REVENUE' : 'EXPENSE');
const isSettled = (transaction: FinancialTransaction) => transaction.type === 'INCOME' ? transaction.status === 'RECEBIDO' : transaction.status === 'PAGO';
export function summarizeCashMovements(transactions: FinancialTransaction[]): CashMovementSummary {
  const totals = transactions.reduce((acc, transaction) => { const amount = clampMoney(transaction.amount); const nature = natureOf(transaction); if (nature === 'COMMERCIAL_DISCOUNT') acc.commercialDiscounts += amount; if (!isSettled(transaction) || nature === 'NON_FINANCIAL' || nature === 'COMMERCIAL_DISCOUNT') return acc; if (transaction.type === 'INCOME') acc.cashIn += amount; else acc.cashOut += amount; if (nature === 'REVENUE' || nature === 'ADVANCE') acc.recognizedRevenue += transaction.type === 'INCOME' ? amount : -amount; if (nature === 'EXPENSE') acc.recognizedExpenses += transaction.type === 'EXPENSE' ? amount : -amount; if (nature === 'PASS_THROUGH') transaction.type === 'INCOME' ? acc.passThroughReceived += amount : acc.passThroughPaid += amount; if (nature === 'INTERNAL_TRANSFER') acc.internalTransferNet += transaction.type === 'INCOME' ? amount : -amount; return acc; }, { cashIn: 0, cashOut: 0, recognizedRevenue: 0, recognizedExpenses: 0, commercialDiscounts: 0, passThroughReceived: 0, passThroughPaid: 0, internalTransferNet: 0 });
  return { cashIn: roundMoney(totals.cashIn), cashOut: roundMoney(totals.cashOut), cashBalance: roundMoney(totals.cashIn - totals.cashOut), recognizedRevenue: roundMoney(totals.recognizedRevenue), recognizedExpenses: roundMoney(totals.recognizedExpenses), commercialDiscounts: roundMoney(totals.commercialDiscounts), passThroughReceived: roundMoney(totals.passThroughReceived), passThroughPaid: roundMoney(totals.passThroughPaid), passThroughBalance: roundMoney(totals.passThroughReceived - totals.passThroughPaid), internalTransferNet: roundMoney(totals.internalTransferNet) };
}
export function isPeriodClosed(dateStr: string, unitId: string, cashClosings: CashClosing[]): boolean { return Boolean(dateStr && unitId && cashClosings.some(closing => closing.unitId === unitId && closing.date === dateStr && closing.status !== 'REOPENED')); }
export function calculateFinancialSummary(entries: DailyEntry[], transactions: FinancialTransaction[], unitId?: string, startDate?: string, endDate?: string): FinancialSummary {
  const inScope = <T extends { unitId?: string; date: string }>(item: T) => (!unitId || item.unitId === unitId) && (!startDate || item.date >= startDate) && (!endDate || item.date <= endDate); const scopedEntries = entries.filter(inScope); const cash = summarizeCashMovements(transactions.filter(inScope));
  const itemSum = (entry: DailyEntry, key: 'amount' | 'commission') => Object.values(entry.items || {}).reduce((sum, item) => sum + clampMoney(item?.[key]), 0);
  const grossRevenue = roundMoney(scopedEntries.reduce((sum, entry) => sum + (typeof entry.totalAmount === 'number' ? clampMoney(entry.totalAmount) : itemSum(entry, 'amount')), 0));
  const courtesyVolume = roundMoney(scopedEntries.reduce((sum, entry) => sum + (typeof entry.courtesyAmount === 'number' ? clampMoney(entry.courtesyAmount) : Object.values(entry.cortesias || {}).reduce((value, item) => value + clampMoney(item?.amount), 0)), 0));
  const internalSales = roundMoney(scopedEntries.reduce((sum, entry) => sum + clampMoney(entry.internalSaleAmount), 0)); const totalCommissions = roundMoney(scopedEntries.reduce((sum, entry) => sum + (typeof entry.commissionAmount === 'number' ? clampMoney(entry.commissionAmount) : itemSum(entry, 'commission')), 0)); const netRevenue = applyCommercialDiscount(grossRevenue, cash.commercialDiscounts);
  return { ...cash, grossRevenue, netRevenue, totalExpenses: cash.recognizedExpenses, totalCommissions, internalSales, courtesyVolume, netCashFlow: cash.cashBalance };
}
