import { FormEvent, useMemo, useState } from "react";
import { Check, Eye, MessageCircle, Megaphone, Reply, Send, Trash2, Users } from "lucide-react";
import { useStore } from "../store";
import { AnnouncementComment, Role, SystemAnnouncement } from "../types";

const ROLE_LABELS: Record<Role | "ALL", string> = { ALL: "Todos os perfis", ADMIN: "Gerência", RECEPTION: "Recepção", FINANCIAL: "Financeiro", MARKETING: "Marketing", BARBER: "Barbeiros", MANICURE: "Manicures" };
const TYPE_LABELS = { INFO: "Informativo", IMPORTANT: "Importante", ALERT: "Urgente", CELEBRATION: "Celebração" } as const;
const TYPE_STYLES = { INFO: "bg-blue-500/10 text-blue-600 dark:text-blue-400", IMPORTANT: "bg-orange-500/10 text-orange-600 dark:text-orange-400", ALERT: "bg-red-500/10 text-red-600 dark:text-red-400", CELEBRATION: "bg-emerald-500/10 text-emerald-600 dark:text-emerald-400" } as const;

export function AnnouncementWall() {
  const { currentUser, announcements, systemUnits, addAnnouncement, updateAnnouncement, deleteAnnouncement } = useStore();
  const canPublish = currentUser?.role === "ADMIN";
  const [content, setContent] = useState(""); const [title, setTitle] = useState("");
  const [unitId, setUnitId] = useState("ALL"); const [targetRole, setTargetRole] = useState<Role | "ALL">("ALL");
  const [type, setType] = useState<SystemAnnouncement["type"]>("INFO"); const [saving, setSaving] = useState(false);
  const [commentText, setCommentText] = useState<Record<string, string>>({});
  const [replyingTo, setReplyingTo] = useState<Record<string, AnnouncementComment | undefined>>({});
  const [expanded, setExpanded] = useState<Record<string, boolean>>({});

  const visibleAnnouncements = useMemo(() => [...(announcements || [])].filter(item => {
    if (currentUser?.role === "ADMIN") return true;
    const unitMatches = item.unitId === "ALL" || (!!currentUser?.unit && item.unitId === currentUser.unit);
    const roleMatches = !item.targetRoles?.length || item.targetRoles.includes(currentUser!.role);
    return unitMatches && roleMatches;
  }).sort((a, b) => b.createdAt.localeCompare(a.createdAt)), [announcements, currentUser]);

  const publish = async (event: FormEvent) => { event.preventDefault(); if (!currentUser || !content.trim()) return; setSaving(true);
    try { await addAnnouncement({ id: crypto.randomUUID(), title: title.trim() || "Novo comunicado", content: content.trim(), type, unitId, targetRoles: targetRole === "ALL" ? [] : [targetRole], createdAt: new Date().toISOString(), createdBy: currentUser.name, createdById: currentUser.id, readBy: [], comments: [] }); setTitle(""); setContent(""); setUnitId("ALL"); setTargetRole("ALL"); setType("INFO"); } finally { setSaving(false); }
  };
  const markSeen = async (item: SystemAnnouncement) => { if (!currentUser || item.readBy?.includes(currentUser.id)) return; await updateAnnouncement({ ...item, readBy: [...(item.readBy || []), currentUser.id] }); };
  const comment = async (item: SystemAnnouncement) => { if (!currentUser || !commentText[item.id]?.trim()) return; const reply = replyingTo[item.id]; const next: AnnouncementComment = { id: crypto.randomUUID(), userId: currentUser.id, userName: currentUser.name, content: commentText[item.id].trim(), createdAt: new Date().toISOString(), replyToId: reply?.id, replyToName: reply?.userName }; await updateAnnouncement({ ...item, comments: [...(item.comments || []), next] }); setCommentText(v => ({ ...v, [item.id]: "" })); setReplyingTo(v => ({ ...v, [item.id]: undefined })); setExpanded(v => ({ ...v, [item.id]: true })); };
  const unitName = (id: string) => id === "ALL" ? "Todas as unidades" : systemUnits.find(unit => unit.id === id)?.name || id;

  return <div className="mx-auto grid max-w-6xl gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
    <section className="space-y-4">
      <header className="app-themed-panel rounded-2xl border border-gray-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><div className="flex items-center gap-3"><span className="rounded-xl bg-[var(--theme-color)]/10 p-3 text-[var(--theme-color)]"><Megaphone /></span><div><h2 className="text-xl font-black">Mural da equipe</h2><p className="text-sm text-gray-500 dark:text-zinc-400">Comunicados, respostas e confirmações de leitura.</p></div></div></header>
      {visibleAnnouncements.map(item => { const seen = !!currentUser && item.readBy?.includes(currentUser.id); const comments = item.comments || []; return <article key={item.id} className="app-themed-panel overflow-hidden rounded-2xl border border-gray-200 bg-white dark:border-zinc-800 dark:bg-zinc-900">
        <div className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex min-w-0 gap-3"><div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-[var(--theme-color)] font-black text-white">{item.createdBy?.slice(0, 1).toUpperCase()}</div><div className="min-w-0"><p className="font-bold">{item.createdBy || "Gerência"}</p><p className="text-xs text-gray-500 dark:text-zinc-400">{new Date(item.createdAt).toLocaleString("pt-BR")}</p></div></div>{canPublish && <button onClick={() => confirm("Excluir este comunicado?") && deleteAnnouncement(item.id)} className="rounded-lg p-2 text-gray-400 hover:bg-red-500/10 hover:text-red-500" aria-label="Excluir"><Trash2 className="h-4 w-4" /></button>}</div>
        <div className="mt-4 flex flex-wrap gap-2"><span className={`rounded-full px-2.5 py-1 text-[10px] font-black uppercase ${TYPE_STYLES[item.type]}`}>{TYPE_LABELS[item.type]}</span><span className="rounded-full bg-gray-100 px-2.5 py-1 text-[10px] font-bold dark:bg-zinc-800">{unitName(item.unitId)}</span><span className="rounded-full bg-gray-100 px-2.5 py-1 text-[10px] font-bold dark:bg-zinc-800">{item.targetRoles?.length ? item.targetRoles.map(role => ROLE_LABELS[role]).join(", ") : "Todos os perfis"}</span></div><h3 className="mt-4 text-lg font-black">{item.title}</h3><p className="mt-2 whitespace-pre-wrap text-sm leading-6 text-gray-700 dark:text-zinc-300">{item.content}</p></div>
        <div className="flex border-t border-gray-100 dark:border-zinc-800"><button onClick={() => markSeen(item)} className={`flex flex-1 items-center justify-center gap-2 px-3 py-3 text-xs font-bold hover:bg-gray-50 dark:hover:bg-zinc-800 ${seen ? "text-emerald-500" : "text-gray-500"}`}><Eye className="h-4 w-4" />{seen ? "Visto" : "Marcar como visto"} <span className="opacity-60">{item.readBy?.length || 0}</span></button><button onClick={() => setExpanded(v => ({ ...v, [item.id]: !v[item.id] }))} className="flex flex-1 items-center justify-center gap-2 border-l border-gray-100 px-3 py-3 text-xs font-bold text-gray-500 hover:bg-gray-50 dark:border-zinc-800 dark:hover:bg-zinc-800"><MessageCircle className="h-4 w-4" />Responder <span className="opacity-60">{comments.length}</span></button></div>
        {(expanded[item.id] || comments.length > 0) && <div className="space-y-3 border-t border-gray-100 bg-gray-50/70 p-4 dark:border-zinc-800 dark:bg-zinc-950/30">{comments.map(entry => <div key={entry.id} className="rounded-xl bg-white p-3 text-sm dark:bg-zinc-800"><div className="flex justify-between gap-2"><strong>{entry.userName}</strong><span className="text-[10px] text-gray-400">{new Date(entry.createdAt).toLocaleString("pt-BR")}</span></div>{entry.replyToName && <p className="mt-1 text-xs text-[var(--theme-color)]">Em resposta a @{entry.replyToName}</p>}<p className="mt-1 text-gray-700 dark:text-zinc-300">{entry.content}</p><button onClick={() => { setReplyingTo(v => ({ ...v, [item.id]: entry })); setExpanded(v => ({ ...v, [item.id]: true })); }} className="mt-2 flex items-center gap-1 text-xs font-bold text-gray-500"><Reply className="h-3 w-3" />Responder</button></div>)}{replyingTo[item.id] && <div className="flex items-center justify-between rounded-lg bg-[var(--theme-color)]/10 px-3 py-2 text-xs">Respondendo a <strong>@{replyingTo[item.id]?.userName}</strong><button onClick={() => setReplyingTo(v => ({ ...v, [item.id]: undefined }))}>×</button></div>}<div className="flex gap-2"><input value={commentText[item.id] || ""} onChange={e => setCommentText(v => ({ ...v, [item.id]: e.target.value }))} onKeyDown={e => { if (e.key === "Enter") comment(item); }} placeholder="Escreva uma resposta..." className="min-w-0 flex-1 rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm outline-none focus:border-[var(--theme-color)] dark:border-zinc-700 dark:bg-zinc-900" /><button onClick={() => comment(item)} className="rounded-xl bg-[var(--theme-color)] p-2.5 text-white"><Send className="h-4 w-4" /></button></div></div>}
      </article>; })}
      {!visibleAnnouncements.length && <div className="rounded-2xl border border-dashed border-gray-300 p-12 text-center text-gray-500 dark:border-zinc-700"><Megaphone className="mx-auto mb-3 h-8 w-8" />Nenhum comunicado destinado ao seu perfil.</div>}
    </section>
    <aside className="space-y-4 lg:sticky lg:top-4 lg:self-start">{canPublish ? <form onSubmit={publish} className="app-themed-panel space-y-3 rounded-2xl border border-gray-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><h3 className="font-black">Nova publicação</h3><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Título (opcional)" className="w-full rounded-xl border border-gray-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700" /><textarea value={content} onChange={e => setContent(e.target.value)} placeholder="O que deseja comunicar?" rows={5} className="w-full resize-none rounded-xl border border-gray-200 bg-transparent px-3 py-2 text-sm dark:border-zinc-700" required /><select value={unitId} onChange={e => setUnitId(e.target.value)} className="w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-900"><option value="ALL">Todas as unidades</option>{systemUnits.map(unit => <option key={unit.id} value={unit.id}>{unit.name}</option>)}</select><select value={targetRole} onChange={e => setTargetRole(e.target.value as Role | "ALL")} className="w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-900">{Object.entries(ROLE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={type} onChange={e => setType(e.target.value as SystemAnnouncement["type"])} className="w-full rounded-xl border border-gray-200 bg-white px-3 py-2 text-sm dark:border-zinc-700 dark:bg-zinc-900">{Object.entries(TYPE_LABELS).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><button disabled={saving} className="flex w-full items-center justify-center gap-2 rounded-xl bg-[var(--theme-color)] px-4 py-3 text-sm font-black text-white disabled:opacity-50"><Send className="h-4 w-4" />{saving ? "Publicando..." : "Publicar"}</button></form> : <div className="rounded-2xl border border-gray-200 bg-white p-5 dark:border-zinc-800 dark:bg-zinc-900"><Users className="mb-3 text-[var(--theme-color)]" /><h3 className="font-black">Seu canal interno</h3><p className="mt-2 text-sm text-gray-500">Aqui aparecem somente mensagens destinadas à sua unidade e ao seu perfil.</p><p className="mt-3 flex items-center gap-2 text-xs font-bold text-emerald-500"><Check className="h-4 w-4" />Leitura sincronizada</p></div>}</aside>
  </div>;
}
