import React, { useMemo, useState } from 'react';
import { ChevronDown, ChevronRight, Download, Landmark, TrendingDown, TrendingUp, WalletCards } from 'lucide-react';
import { useStore } from '../store';
import { buildCashFlowStatement } from '../services/cashFlowStatement';
import { loadPdfExporter, loadXlsx } from '../services/lazyLibraries';
import { AppBadge, AppButton, AppCard, AppEmptyState, AppSectionHeader, appControlClass } from './ui/AppPrimitives';

const money=(value:number)=>value.toLocaleString('pt-BR',{style:'currency',currency:'BRL'});

export function CashFlowStatementView({period}:{period:string}){
  const {transactions,systemUnits,currentUser,finClassifications,finSubclassifications}=useStore();
  const [unitId,setUnitId]=useState(currentUser?.role==='ADMIN'?'ALL':currentUser?.unitIds?.[0]||'ALL');
  const [expanded,setExpanded]=useState<Set<string>>(new Set(['OPERATING']));
  const classificationNames=useMemo(()=>Object.fromEntries(finClassifications.map(item=>[item.id,item.name])),[finClassifications]);
  const subclassificationNames=useMemo(()=>Object.fromEntries(finSubclassifications.map(item=>[item.id,item.name])),[finSubclassifications]);
  const statement=useMemo(()=>buildCashFlowStatement(transactions,{period,unitId,classificationNames,subclassificationNames}),[transactions,period,unitId,classificationNames,subclassificationNames]);
  const unitName=unitId==='ALL'?'Consolidado — todas as unidades':systemUnits.find(item=>item.id===unitId)?.name||unitId;
  const toggle=(key:string)=>setExpanded(current=>{const next=new Set(current);if(next.has(key))next.delete(key);else next.add(key);return next;});
  const exportReport=async(format:'xlsx'|'pdf')=>{const rows=statement.sections.flatMap(section=>[{Grupo:section.label,Categoria:'TOTAL DO GRUPO',Subcategoria:'',Entradas:section.inflow,Saídas:section.outflow,Saldo:section.balance},...section.lines.map(line=>({Grupo:section.label,Categoria:line.category,Subcategoria:line.subcategory,Entradas:line.inflow,Saídas:line.outflow,Saldo:line.balance}))]);if(format==='xlsx'){const XLSX=await loadXlsx(),book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet([{Indicador:'Saldo inicial',Valor:statement.openingBalance},{Indicador:'Entradas',Valor:statement.periodInflow},{Indicador:'Saídas',Valor:statement.periodOutflow},{Indicador:'Variação líquida',Valor:statement.netChange},{Indicador:'Saldo final',Valor:statement.closingBalance}]),'Resumo');XLSX.utils.book_append_sheet(book,XLSX.utils.json_to_sheet(rows),'DFC');XLSX.writeFile(book,`DFC_${period}_${unitName.replace(/\W+/g,'_')}.xlsx`);return;}const{jsPDF}=await loadPdfExporter(),pdf=new jsPDF({orientation:'landscape',unit:'mm',format:'a4'});pdf.setFontSize(16);pdf.text('Demonstração dos Fluxos de Caixa',14,15);pdf.setFontSize(9);pdf.text(`${unitName} · ${period} · Método direto · Regime de caixa`,14,22);let y=32;for(const row of rows){if(y>190){pdf.addPage();y=15;}pdf.setFontSize(row.Categoria==='TOTAL DO GRUPO'?10:8);pdf.text(`${row.Grupo} | ${row.Categoria} | ${row.Subcategoria} | Entradas ${money(row.Entradas)} | Saídas ${money(row.Saídas)} | Saldo ${money(row.Saldo)}`.slice(0,180),14,y);y+=6;}pdf.setFontSize(11);pdf.text(`Saldo final calculado: ${money(statement.closingBalance)}`,14,200);pdf.save(`DFC_${period}_${unitName.replace(/\W+/g,'_')}.pdf`);};
  return <div className="space-y-5">
    <AppCard className="p-4 sm:p-5"><div className="flex flex-col gap-4 lg:flex-row lg:items-start lg:justify-between"><AppSectionHeader title="Demonstração dos Fluxos de Caixa" description="Método direto e regime de caixa, calculado somente com lançamentos pagos ou recebidos."/><div className="flex flex-wrap gap-2"><select className={appControlClass} value={unitId} onChange={event=>setUnitId(event.target.value)}>{currentUser?.role==='ADMIN'&&<option value="ALL">Todas as unidades</option>}{systemUnits.filter(item=>item.isActive!==false&&(currentUser?.role==='ADMIN'||currentUser?.unitIds?.includes(item.id))).map(item=><option key={item.id} value={item.id}>{item.name}</option>)}</select><AppButton onClick={()=>void exportReport('xlsx')}><Download className="h-4 w-4"/>Excel</AppButton><AppButton onClick={()=>void exportReport('pdf')}><Download className="h-4 w-4"/>PDF</AppButton></div></div><div className="mt-4 flex flex-wrap gap-2"><AppBadge tone="success">Realizado</AppBadge><AppBadge tone="neutral">{unitName}</AppBadge><AppBadge tone="neutral">{period}</AppBadge>{statement.ignoredCount>0&&<AppBadge tone="warning">{statement.ignoredCount} movimentos neutros desconsiderados</AppBadge>}</div></AppCard>
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Metric label="Saldo inicial acumulado" value={statement.openingBalance} icon={WalletCards}/><Metric label="Entradas realizadas" value={statement.periodInflow} icon={TrendingUp} tone="positive"/><Metric label="Saídas realizadas" value={statement.periodOutflow} icon={TrendingDown} tone="negative"/><Metric label="Variação líquida" value={statement.netChange} icon={Landmark} tone={statement.netChange>=0?'positive':'negative'}/><Metric label="Saldo final calculado" value={statement.closingBalance} icon={WalletCards} tone={statement.closingBalance>=0?'positive':'negative'}/></div>
    <AppCard className="overflow-x-auto app-scrollbar"><div className="min-w-[680px]"><div className="grid grid-cols-[minmax(0,1fr)_repeat(3,minmax(110px,160px))] gap-3 border-b border-gray-200 bg-gray-50 px-4 py-3 text-[10px] font-black uppercase text-gray-500 dark:border-zinc-800 dark:bg-zinc-950"><span>Grupo / categoria</span><span className="text-right">Entradas</span><span className="text-right">Saídas</span><span className="text-right">Saldo</span></div>{statement.transactionCount===0?<AppEmptyState title="Nenhum movimento realizado no período" description="A DFC será preenchida automaticamente quando receitas forem recebidas e despesas forem pagas." icon={<Landmark/>}/>:statement.sections.map(section=><div key={section.group} className="border-b border-gray-200 last:border-0 dark:border-zinc-800"><button onClick={()=>toggle(section.group)} className="grid w-full grid-cols-[minmax(0,1fr)_repeat(3,minmax(110px,160px))] gap-3 px-4 py-4 text-left hover:bg-gray-50 dark:hover:bg-zinc-800/40"><span className="flex items-center gap-2 font-black">{expanded.has(section.group)?<ChevronDown className="h-4 w-4"/>:<ChevronRight className="h-4 w-4"/>}{section.label}</span><span className="text-right font-bold text-emerald-600">{money(section.inflow)}</span><span className="text-right font-bold text-red-500">{money(section.outflow)}</span><span className={`text-right font-black ${section.balance>=0?'text-emerald-600':'text-red-500'}`}>{money(section.balance)}</span></button>{expanded.has(section.group)&&<div className="bg-gray-50/60 px-4 pb-3 dark:bg-zinc-950/30">{section.lines.length?section.lines.map(line=><details key={line.key} className="border-t border-gray-200 dark:border-zinc-800"><summary className="grid cursor-pointer grid-cols-[minmax(0,1fr)_repeat(3,minmax(110px,160px))] gap-3 py-3 text-xs"><span><strong>{line.category}</strong><span className="block text-[10px] text-gray-400">{line.subcategory} · {line.transactions.length} lançamento(s)</span></span><span className="text-right text-emerald-600">{money(line.inflow)}</span><span className="text-right text-red-500">{money(line.outflow)}</span><span className="text-right font-bold">{money(line.balance)}</span></summary><div className="space-y-1 pb-3">{line.transactions.map(item=><div key={item.id} className="grid gap-1 rounded-lg bg-white px-3 py-2 text-[11px] dark:bg-zinc-900 sm:grid-cols-[100px_minmax(0,1fr)_130px]"><span>{new Date(`${item.date}T12:00:00`).toLocaleDateString('pt-BR')}</span><span>{item.description}</span><strong className={`text-right ${item.type==='INCOME'?'text-emerald-600':'text-red-500'}`}>{item.type==='INCOME'?'+ ':'- '}{money(item.amount)}</strong></div>)}</div></details>):<p className="py-3 text-xs text-gray-400">Nenhum movimento neste grupo.</p>}</div>}</div>)}</div></AppCard>
    <div className="rounded-xl border border-blue-200 bg-blue-50 p-4 text-xs text-blue-900 dark:border-blue-900 dark:bg-blue-950/30 dark:text-blue-200"><strong>Critério da apuração:</strong> receitas entram quando estão como “Recebido” e despesas quando estão como “Pago”. Cortesias, descontos comerciais e transferências internas não alteram a DFC consolidada.</div>
  </div>;
}

function Metric({label,value,icon:Icon,tone}:{label:string;value:number;icon:React.ComponentType<{className?:string}>;tone?:'positive'|'negative'}){return <AppCard className="p-4"><div className="flex items-center justify-between"><span className="text-[10px] font-black uppercase text-gray-400">{label}</span><Icon className="h-4 w-4 text-[var(--theme-color)]"/></div><strong className={`mt-2 block text-xl ${tone==='positive'?'text-emerald-600':tone==='negative'?'text-red-500':''}`}>{money(value)}</strong></AppCard>}
